# Generated by Django 5.1.7 on 2025-03-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque atual'),
        ),
    ]
