# Generated by Django 5.1.7 on 2025-04-21 19:03

import django.db.models.deletion
import plataforma_de_servicos.produto.models.produto_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('categoria',), 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produtos')),
                ('order', plataforma_de_servicos.produto.models.produto_model.OrderField()),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['order'],
            },
        ),
    ]
