# Generated by Django 5.1.7 on 2025-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_categoria_options_alter_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
