# Generated by Django 5.1.7 on 2025-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
