# Generated by Django 5.1.7 on 2026-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_atributo_alter_produto_estoque_alter_produto_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoratributo',
            name='percentual_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual a ser adicionado ao preço base (ex: 10,00 para 10%)', max_digits=5, verbose_name='Percentual adicional'),
        ),
        migrations.AddField(
            model_name='valoratributo',
            name='preco_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo a ser adicionado ao preço base (ex: R$ 5,00)', max_digits=10, verbose_name='Preço adicional'),
        ),
    ]
