# Generated by Django 5.1.7 on 2026-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_add_price_modifiers_to_valor_atributo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço'),
        ),
    ]
