# Generated by Django 5.1.7 on 2026-01-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_allow_null_preco_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do produto', null=True, verbose_name='descrição'),
        ),
    ]
