# Generated by Django 5.1.7 on 2026-01-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_add_descricao_to_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoratributo',
            name='percentual_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentual a ser adicionado ao preço base (ex: 10 para 10%). Não pode ser usado junto com preço adicional.', max_digits=5, verbose_name='Percentual adicional'),
        ),
        migrations.AlterField(
            model_name='valoratributo',
            name='preco_adicional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor fixo a ser adicionado ao preço base. Não pode ser usado junto com percentual.', max_digits=10, verbose_name='Preço adicional'),
        ),
    ]
