# Generated by Django 5.1.7 on 2026-01-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_allow_blank_price_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o preço base do produto. Se preenchido, SUBSTITUI o preço base (não soma).', max_digits=10, null=True, verbose_name='preço'),
        ),
    ]
