# Generated by Django 5.1.7 on 2026-01-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Marque para exibir o produto na vitrine.', verbose_name='Disponível'),
        ),
    ]
