# Generated by Django 5.1.7 on 2026-01-31 20:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('produto', '0012_produto_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nome',
            field=models.CharField(help_text='Ex: Cor, Tamanho', max_length=50),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='produto'),
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'categoria')},
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('empresa', 'produto')},
        ),
        migrations.AddConstraint(
            model_name='atributo',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='unique_empresa_atributo_slug'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='unique_empresa_categoria_slug'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='unique_empresa_produto_slug'),
        ),
    ]
