# Generated by Django 5.1.7 on 2026-02-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_atributo_add_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributo',
            name='multipla_selecao',
            field=models.BooleanField(default=False, help_text="Se marcado, o usuário pode selecionar vários valores deste atributo. Ex: 'Extras' pode ter múltiplos valores. Se desmarcado, apenas um valor pode ser selecionado. Ex: 'Cor' geralmente permite apenas uma seleção.", verbose_name='Permite múltipla seleção'),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nome',
            field=models.CharField(help_text='Ex: Cor, Tamanho, Motor', max_length=50),
        ),
    ]
