# Generated by Django 5.1.7 on 2026-02-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['usuario__name'], 'verbose_name': 'funcionário', 'verbose_name_plural': 'funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_corretor',
            field=models.BooleanField(default=False, help_text='Indica se o funcionário atua como corretor/vendedor', verbose_name='é corretor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, help_text="CPF no formato 'XXX.XXX.XXX-XX'", max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='is_signatario',
            field=models.BooleanField(default=False, verbose_name='é signatário'),
        ),
    ]
