# Generated by Django 5.1.7 on 2026-02-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_add_admin_ui_customization'),
        ('users', '0003_add_telefone_to_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o usuário pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
