# Generated by Django 5.1.7 on 2026-02-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_empresa_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='papel',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('ADMIN', 'Administrador')], default='VENDEDOR', help_text='Define o nível de acesso do funcionário no sistema', max_length=20, verbose_name='papel'),
        ),
    ]
