# Generated by Django 5.1.7 on 2026-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('site_name', models.CharField(default='Plataforma de Serviços', help_text='Título exibido no navbar', max_length=100, verbose_name='Nome do Site')),
                ('hero_title', models.CharField(default='Pizzas Artesanais, Sabor Inesquecível', max_length=200, verbose_name='Título do Banner')),
                ('hero_description', models.TextField(default='Feitas com os melhores ingredientes, direto do forno para sua casa.', verbose_name='Descrição do Banner')),
                ('hero_button_text', models.CharField(default='Ver o Cardápio', max_length=50, verbose_name='Texto do Botão')),
                ('hero_image', models.ImageField(blank=True, help_text='Upload de imagem para o banner. Se não fornecida, usa a URL abaixo.', null=True, upload_to='site/', verbose_name='Imagem do Banner')),
                ('hero_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=2070&auto=format&fit=crop', help_text='URL externa para imagem do banner (usada se não houver upload)', verbose_name='URL da Imagem do Banner')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
