# Generated by Django 5.1.7 on 2026-01-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_site_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_button_text',
            field=models.CharField(default='Ver Ofertas', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_description',
            field=models.TextField(default='Encontre carros, motos e imóveis selecionados com as melhores condições do mercado.', verbose_name='Descrição do Banner'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=2083&auto=format&fit=crop', help_text='URL externa para imagem do banner (usada se não houver upload)', verbose_name='URL da Imagem do Banner'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='Veículos e Imóveis Premium', max_length=200, verbose_name='Título do Banner'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='AutoPrime', help_text='Título exibido no navbar', max_length=100, verbose_name='Nome do Site'),
        ),
    ]
