# Generated by Django 5.1.7 on 2026-02-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteconfig_hero_button_text_and_more'),
        ('empresa', '0003_add_admin_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='empresa',
            field=models.OneToOneField(blank=True, help_text='Empresa dona desta configuração de site', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_config', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
