# Generated by Django 5.1.7 on 2026-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_empresa_to_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo exibido no navbar (recomendado: altura de 40-50px)', null=True, upload_to='site/logos/', verbose_name='Logo do Site'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='theme',
            field=models.CharField(choices=[('default', 'Padrão'), ('dark', 'Escuro'), ('nature', 'Natureza'), ('luxury', 'Luxo'), ('energy', 'Energia'), ('axe', 'Axé'), ('ocean', 'Oceano'), ('rose', 'Rosa'), ('earth', 'Terra'), ('minimal', 'Minimalista'), ('gatopreto', 'Gato Preto'), ('mystic', 'Místico')], default='default', help_text='Tema de cores do site', max_length=20, verbose_name='Tema'),
        ),
    ]
