# Generated by Django 5.1.7 on 2025-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventario_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariosaldo',
            options={'ordering': ('produto',), 'verbose_name': 'Saldo de Inventário', 'verbose_name_plural': 'Saldos de Inventário'},
        ),
    ]
