# Generated by Django 5.1.7 on 2026-01-31 20:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('inventario', '0004_inventario_exibir_na_vitrine'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='nome', verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='unique_empresa_inventario_slug'),
        ),
    ]
