# Generated by Django 5.1.7 on 2026-02-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_inventario_empresa_alter_inventario_nome_and_more'),
        ('produto', '0015_add_multipla_selecao_to_atributo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariosaldo',
            options={'ordering': ('produto', 'variacao'), 'verbose_name': 'Saldo de Inventário', 'verbose_name_plural': 'Saldos de Inventário'},
        ),
        migrations.AlterUniqueTogether(
            name='inventariosaldo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventariosaldo',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.variacaoproduto', verbose_name='Variação'),
        ),
        migrations.AlterUniqueTogether(
            name='inventariosaldo',
            unique_together={('inventario', 'produto', 'variacao')},
        ),
    ]
