# Generated by Django 5.1.7 on 2026-02-04 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_make_foto_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='admin_url',
            field=models.CharField(default='gerentes', help_text="Endpoint do painel administrativo (ex: 'gerentes' → /gerentes/). Use apenas letras minúsculas, números e hífens.", max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números e hífens.', regex='^[a-z0-9-]+$')], verbose_name='URL do Admin'),
        ),
    ]
