# Generated by Django 5.1.7 on 2026-02-05 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_add_admin_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Cor para elementos de destaque (hex). Ex: #f59e0b (amarelo)', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal. Ex: #f59e0b', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor de Destaque'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='admin_favicon',
            field=models.ImageField(blank=True, help_text='Ícone exibido na aba do navegador (recomendado: 32x32px).', null=True, upload_to='empresas/favicons/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='admin_logo',
            field=models.ImageField(blank=True, help_text='Logo exibido no cabeçalho do painel (recomendado: 180x40px).', null=True, upload_to='empresas/logos/', verbose_name='Logo do Admin'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='admin_subtitle',
            field=models.CharField(blank=True, help_text='Subtítulo exibido abaixo do título no painel administrativo.', max_length=150, verbose_name='Subtítulo do Admin'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='admin_title',
            field=models.CharField(blank=True, help_text='Título exibido no cabeçalho do painel administrativo. Se vazio, usa o nome da empresa.', max_length=100, verbose_name='Título do Admin'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='footer_text',
            field=models.CharField(blank=True, help_text="Texto exibido no rodapé do admin. Ex: '© 2024 Sua Empresa'", max_length=200, verbose_name='Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='primary_color',
            field=models.CharField(default='#0ea5e9', help_text='Cor principal do tema (hex). Ex: #0ea5e9 (azul)', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal. Ex: #0ea5e9', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='secondary_color',
            field=models.CharField(default='#64748b', help_text='Cor secundária do tema (hex). Ex: #64748b (cinza)', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal. Ex: #64748b', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sidebar_style',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='dark', help_text='Tema do menu lateral.', max_length=10, verbose_name='Estilo do Sidebar'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Mensagem exibida na página inicial do admin.', verbose_name='Mensagem de Boas-vindas'),
        ),
    ]
