# Generated by Django 5.1.7 on 2026-02-14 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_add_admin_ui_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='vendedor_url',
            field=models.CharField(default='vendedores', help_text="Endpoint do painel de vendedores (ex: 'vendedores' → /vendedores/). Use apenas letras minúsculas, números e hífens.", max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números e hífens.', regex='^[a-z0-9-]+$')], verbose_name='URL do Portal de Vendedores'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='admin_url',
            field=models.CharField(default='gerentes', help_text="Endpoint do painel de gerentes (ex: 'gerentes' → /gerentes/). Use apenas letras minúsculas, números e hífens.", max_length=50, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números e hífens.', regex='^[a-z0-9-]+$')], verbose_name='URL do Portal de Gerentes'),
        ),
    ]
