# Generated by Django 5.1.7 on 2026-02-18 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_add_vendedor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='schema_criado',
            field=models.BooleanField(default=False, editable=False, help_text='Indica se o schema PostgreSQL foi criado.', verbose_name='Schema Provisionado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='schema_criado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Criação do Schema'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='schema_name',
            field=models.CharField(blank=True, help_text='Nome do schema PostgreSQL. Auto-gerado a partir do slug se não informado.', max_length=63, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Schema deve iniciar com letra minúscula e conter apenas letras, números e underscore.', regex='^[a-z][a-z0-9_]*$')], verbose_name='Nome do Schema'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_isolamento',
            field=models.CharField(choices=[('COMPARTILHADO', 'Banco Compartilhado (Padrão)'), ('DEDICADO', 'Banco Dedicado (Schema PostgreSQL)')], default='COMPARTILHADO', help_text='Compartilhado: dados filtrados por empresa na mesma tabela (padrão). Dedicado: schema PostgreSQL exclusivo para maior isolamento.', max_length=20, verbose_name='Tipo de Isolamento de Dados'),
        ),
    ]
