# Generated by Django 5.1.7 on 2026-01-25 21:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corretor', '0002_interessecompra_iteminteresse'),
        ('produto', '0011_alter_produto_preco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('numero', models.CharField(help_text='Número único da ordem (ex: OC-2026-00001)', max_length=20, unique=True, verbose_name='número')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='nome do cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='e-mail do cliente')),
                ('telefone_cliente', models.CharField(max_length=20, verbose_name='telefone do cliente')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor total')),
                ('status', models.CharField(choices=[('PENDENTE_APROVACAO', 'Pendente de Aprovação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('FATURADA', 'Faturada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE_APROVACAO', max_length=20, verbose_name='status')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='data de aprovação')),
                ('motivo_rejeicao', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='corretor.corretor', verbose_name='corretor responsável')),
                ('interesse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_compra', to='corretor.interessecompra', verbose_name='interesse de origem')),
            ],
            options={
                'verbose_name': 'ordem de compra',
                'verbose_name_plural': 'ordens de compra',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(help_text='Nome do produto no momento da criação da ordem', max_length=255, verbose_name='nome do produto')),
                ('variacao_info', models.CharField(blank=True, help_text='Descrição da variação (ex: Cor: Azul, Tamanho: M)', max_length=255, verbose_name='informações da variação')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.produto', verbose_name='produto')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produto.variacaoproduto', verbose_name='variação')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.ordemcompra', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'item da ordem',
                'verbose_name_plural': 'itens da ordem',
            },
        ),
    ]
