# Generated by Django 5.1.7 on 2026-01-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('vendas', '0001_ordem_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_compra', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='numero',
            field=models.CharField(help_text='Número único da ordem (ex: OC-2026-00001)', max_length=20, verbose_name='número'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemcompra',
            unique_together={('empresa', 'numero')},
        ),
    ]
