# Generated by Django 5.1.7 on 2026-02-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_empresa_to_user'),
        ('vendas', '0002_ordemcompra_empresa_alter_ordemcompra_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcompra',
            name='corretor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_corretor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens', to='users.funcionario', verbose_name='corretor responsável'),
        ),
    ]
