# Generated by Django 5.1.7 on 2026-02-14 22:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_add_admin_ui_customization'),
        ('produto', '0015_add_multipla_selecao_to_atributo'),
        ('users', '0005_add_papel_to_funcionario'),
        ('vendas', '0003_change_interessecompra_corretor_to_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('percentual_padrao', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Percentual padrão de comissão para todos os vendedores', max_digits=5, verbose_name='Percentual Padrão')),
                ('aplica_sobre_desconto', models.BooleanField(default=True, help_text='Se marcado, a comissão é calculada sobre o valor final (com desconto)', verbose_name='Aplica sobre valor com desconto')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_comissao', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Comissão',
                'verbose_name_plural': 'Configurações de Comissão',
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de comissão (ex: 5.00 para 5%)', max_digits=5, verbose_name='Percentual')),
                ('valor_base', models.DecimalField(decimal_places=2, help_text='Valor total da ordem sobre o qual a comissão é calculada', max_digits=10, verbose_name='Valor Base')),
                ('valor_comissao', models.DecimalField(decimal_places=2, help_text='Valor calculado da comissão (valor_base * percentual / 100)', max_digits=10, verbose_name='Valor da Comissão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='empresa.empresa', verbose_name='Empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='users.funcionario', verbose_name='Vendedor')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='vendas.ordemcompra', verbose_name='Ordem de Compra')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-created'],
                'unique_together': {('ordem', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='ComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de comissão para este vendedor', max_digits=5, verbose_name='Percentual')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_configuradas', to='users.funcionario', verbose_name='Vendedor')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_vendedor', to='vendas.configuracaocomissao', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Comissão por Vendedor',
                'verbose_name_plural': 'Comissões por Vendedor',
                'unique_together': {('configuracao', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='ComissaoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de comissão para esta categoria', max_digits=5, verbose_name='Percentual')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_configuradas', to='produto.categoria', verbose_name='Categoria')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_categoria', to='vendas.configuracaocomissao', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Comissão por Categoria',
                'verbose_name_plural': 'Comissões por Categoria',
                'unique_together': {('configuracao', 'categoria')},
            },
        ),
    ]
