# Generated by Django 5.1.7 on 2026-01-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0006_add_price_modifiers_to_valor_atributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Chave da sessão do usuário', max_length=40)),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('variacao_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.variacaoproduto')),
            ],
            options={
                'verbose_name': 'Reserva de Estoque',
                'verbose_name_plural': 'Reservas de Estoque',
                'unique_together': {('session_key', 'produto', 'variacao_produto')},
            },
        ),
    ]
