# Generated by Django 5.1.7 on 2026-01-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('produto', '0007_allow_null_preco_variacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservaestoque',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservaestoque',
            constraint=models.UniqueConstraint(condition=models.Q(('variacao_produto__isnull', True)), fields=('session_key', 'produto'), name='unique_reserva_produto_sem_variacao'),
        ),
        migrations.AddConstraint(
            model_name='reservaestoque',
            constraint=models.UniqueConstraint(fields=('session_key', 'variacao_produto'), name='unique_reserva_variacao'),
        ),
    ]
