# Generated by Django 5.1.7 on 2026-01-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('payment', '0004_order_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
