# Generated by Django 5.1.7 on 2025-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='nota fiscal')),
                ('movimento', models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saída')], max_length=1)),
                ('processado', models.BooleanField(default=False)),
                ('data', models.DateField(auto_now_add=True, help_text='Data do movimento', verbose_name='data')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens do registro de estoque',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ProtocoloEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('estoque_atualizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'protocolo de entrega',
                'verbose_name_plural': 'protocolos de entrega',
            },
        ),
        migrations.CreateModel(
            name='ProtocoloEntregaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
