# Generated by Django 5.1.7 on 2025-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('e', 'Entrada'), ('s', 'Saída'), ('t', 'Transferência')], max_length=1),
        ),
    ]
