# Generated by Django 5.1.7 on 2026-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoque_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o movimento', null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='origem_saida',
            field=models.CharField(blank=True, choices=[('pedido', 'Pedido/Venda'), ('perda', 'Perda/Avaria'), ('devolucao', 'Devolução'), ('ajuste', 'Ajuste de Inventário'), ('transferencia', 'Transferência'), ('outros', 'Outros')], help_text='Motivo/origem da saída de estoque', max_length=15, null=True, verbose_name='Origem da Saída'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='pedido_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID do pedido quando a saída é originada de uma venda', null=True, verbose_name='ID do Pedido'),
        ),
    ]
