# Generated by Django 5.1.7 on 2026-01-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_allow_null_funcionario'),
        ('produto', '0011_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='variacao',
            field=models.ForeignKey(blank=True, help_text='Selecione a variação do produto (se houver). O estoque será descontado da variação.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoque_itens', to='produto.variacaoproduto', verbose_name='Variação'),
        ),
    ]
