# Generated by Django 5.1.7 on 2026-01-29 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_add_variacao_to_estoqueitens'),
        ('vendas', '0001_ordem_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
            ],
            options={
                'verbose_name': 'Transferencia entre inventário',
                'verbose_name_plural': 'Transferencias entre inventários',
                'ordering': ('-created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='pedido_id',
        ),
        migrations.AddField(
            model_name='estoque',
            name='ordem_compra',
            field=models.ForeignKey(blank=True, help_text='Ordem de compra que originou esta saída de estoque', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque', to='vendas.ordemcompra', verbose_name='Ordem de Compra'),
        ),
    ]
