# Generated by Django 5.1.7 on 2026-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_estoque_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='saldo_anterior',
            field=models.PositiveIntegerField(blank=True, help_text='Saldo da variação/produto antes da operação (fotografia histórica)', null=True, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='saldo',
            field=models.PositiveIntegerField(blank=True, help_text='Saldo da variação/produto após a operação', null=True, verbose_name='Saldo Após'),
        ),
    ]
