# Generated by Django 5.1.7 on 2026-02-24 02:11

from django.db import migrations


def fix_saidas_sem_empresa(apps, schema_editor):
    """
    Corrige registros de saída de estoque que foram criados sem empresa.
    Atualiza o campo empresa baseado na ordem de compra associada.
    """
    Estoque = apps.get_model('estoque', 'Estoque')

    # Buscar saídas sem empresa que têm ordem de compra associada
    saidas_sem_empresa = Estoque.objects.filter(
        empresa__isnull=True,
        ordem_compra__isnull=False,
    ).select_related('ordem_compra')

    count = 0
    for saida in saidas_sem_empresa:
        if saida.ordem_compra and saida.ordem_compra.empresa:
            saida.empresa = saida.ordem_compra.empresa
            saida.save(update_fields=['empresa'])
            count += 1

    if count > 0:
        print(f"\n  Corrigidos {count} registros de saída de estoque sem empresa.")


def reverse_fix(apps, schema_editor):
    """
    Reverter não faz sentido neste caso - não vamos remover a empresa.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_add_saldo_anterior'),
    ]

    operations = [
        migrations.RunPython(fix_saidas_sem_empresa, reverse_fix),
    ]
