# Generated by Django 5.1.7 on 2026-01-23 23:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='nome do cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='e-mail do cliente')),
                ('telefone_cliente', models.CharField(max_length=20, verbose_name='telefone do cliente')),
                ('mensagem', models.TextField(blank=True, help_text='Observações adicionais do cliente', verbose_name='mensagem')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor total')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], default='NOVO', max_length=20, verbose_name='status')),
                ('corretor', models.ForeignKey(blank=True, help_text='Corretor que está atendendo este lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interesses', to='corretor.corretor', verbose_name='corretor responsável')),
            ],
            options={
                'verbose_name': 'interesse de compra',
                'verbose_name_plural': 'interesses de compra',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ItemInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=255, verbose_name='produto')),
                ('variacao_info', models.CharField(blank=True, help_text='Informações da variação (ex: Cor: Azul, Tamanho: M)', max_length=255, verbose_name='variação')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='corretor.interessecompra', verbose_name='interesse')),
            ],
            options={
                'verbose_name': 'item do interesse',
                'verbose_name_plural': 'itens do interesse',
            },
        ),
    ]
