# Generated by Django 5.1.7 on 2026-01-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0002_interessecompra_iteminteresse'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corretores', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='interessecompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interesses_compra', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterUniqueTogether(
            name='corretor',
            unique_together={('empresa', 'email')},
        ),
    ]
