# Generated by Django 5.1.7 on 2026-02-09 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0003_corretor_empresa_interessecompra_empresa_and_more'),
        ('users', '0002_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretor',
            options={'ordering': ['funcionario__usuario__name'], 'verbose_name': 'corretor', 'verbose_name_plural': 'corretores'},
        ),
        migrations.AlterUniqueTogether(
            name='corretor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='corretor',
            name='funcionario',
            field=models.OneToOneField(blank=True, help_text='Funcionário que atua como corretor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corretor', to='users.funcionario', verbose_name='funcionário'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail de contato (se vazio, usa o e-mail do usuário)', max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome de exibição (se vazio, usa o nome do usuário)', max_length=255, verbose_name='nome'),
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='user',
        ),
    ]
