# Generated by Django 5.1.7 on 2026-02-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0004_link_corretor_to_funcionario'),
        ('users', '0004_add_empresa_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='funcionario',
        ),
        migrations.AlterField(
            model_name='interessecompra',
            name='corretor',
            field=models.ForeignKey(blank=True, help_text='Funcionário/corretor que está atendendo este lead', limit_choices_to={'is_corretor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interesses', to='users.funcionario', verbose_name='corretor responsável'),
        ),
    ]
