# Generated by Django 5.1.7 on 2026-02-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0005_change_interessecompra_corretor_to_funcionario'),
        ('vendas', '0003_change_interessecompra_corretor_to_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corretor',
        ),
    ]
