# Generated by Django 5.1.7 on 2026-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0006_change_interessecompra_corretor_to_funcionario'),
    ]

    operations = [
        # 1. Add the field without unique constraint
        migrations.AddField(
            model_name='interessecompra',
            name='numero',
            field=models.CharField(blank=True, help_text='Número único do interesse por empresa (ex: IC-2026-00001)', max_length=20, verbose_name='número'),
        ),
    ]
