# Generated by Django 5.1.7 on 2025-04-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('data_entrada', models.DateField()),
                ('aprovacao', models.BooleanField(default=False)),
                ('prazo_entrega', models.IntegerField()),
                ('status_servico', models.CharField(choices=[('AGUARDANDO_ORCAMENTO', 'Aguardando Orçamento'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('EM_FATURAMENTO', 'Em Faturamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], max_length=50)),
                ('data_da_aprovacao', models.DateField(blank=True, null=True)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
    ]
