# Generated by Django 5.1.7 on 2025-04-06 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('data_entrada', models.DateField()),
                ('aprovacao', models.BooleanField(default=False)),
                ('prazo_entrega', models.IntegerField()),
                ('status', models.CharField(choices=[('carrinho', 'Carrinho (em construção)'), ('pendente_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago (Em processamento)'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=50)),
                ('data_da_aprovacao', models.DateField(blank=True, null=True)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.carrinho')),
            ],
        ),
    ]
