# Generated by Django 5.1.7 on 2026-01-31 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='carrinho',
            unique_together={('empresa', 'slug')},
        ),
    ]
